# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
# CircleCI maintains a library of pre-built images
# documented at https://circleci.com/docs/2.0/circleci-images/

version: 2
jobs:
  python36:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo pip install tox
      - run:
          name: run tests
          command: |
            tox -e py36

  python37:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo pip install tox
      - run:
          name: run tests
          command: |
            tox -e py37

  python38:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo pip install tox
      - run:
          name: run tests
          command: |
            tox -e py38

  flake8:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo pip install tox
      - run:
          name: run tests
          command: |
            tox -e flake8

  black:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo pip install tox
      - run:
          name: run tests
          command: |
            tox -e black
workflows:
  version: 2
  run_all_tests:
    jobs:
      - python36
      - python37
      - python38
      - flake8
      - black